### ISSUE TITLE
USER STORY: Booking Date and Arrival Time

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#1]
As a  **user**  I can **select date and time** so that ** I can manage my booking**

## Acceptance Criteria
*  The user should be able to see a date picker and calendar widget to select the desired date and time.
*  The user is only allowed to submit the booking if the date and arrival time is valid
*  The user is notified  through a display message if the date and arrival time input is invalid

## Task
- [x] Design and implement a date picker and calendar widget interface for the selection
- [x] Create functionality to display an error message if the selected date and arrival time are invalid
- [x] Test  the date picker and calendar widget are functioning  correctly
