### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#11]
As a  **user**  I can **access the site navigation ** so that ** I can explore different sections of the website easily and mobile-friendly design  for easy navigation on smaller devices**

## Acceptance Criteria
* The navigation menu should include all the main sections of the website including the "Sign Up or Login" button
* The navigation menu should be responsive to different screen sizes
* The menu item should take the user to the corresponding page without broken links

## Task
- [x] Create links for these sections including buttons for "Login or Sign Up"
- [x] Verify that the navigation menu is consistent across all pages of the website
- [x] Create a hamburger menu for smaller devices
- [x] Test the navigation menu to ensure that all sections are displayed correctly
