### ISSUE TITLE
USER STORY: Booking History

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#2]
As a  **user**  I can **view my booking details and history** so that ** I can review and revisit my booking **

## Acceptance Criteria
* The user should be able to access the "Booking details" on the reservations page only when the user is login
* Each Booking entry should display the username or name, contact number, date of booking, arrival time, number of attendees, and optional special requirements
* The user should be able to access easily the "Reservations" page from the navigation menu 

## Task
- [x] Set up an authentication mechanism for user login
- [x] Create a button and links to allow the user to access the reservation page easily
- [x] Create a database schema to store booking information
