### ISSUE TITLE
USER STORY: Cancel and Amend Booking

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#3]
As a  **user**  I can ** cancel and amend my booking** so that ** I have my options for any change of mind**

## Acceptance Criteria
* Cancel Booking
  * When the user selects the "Cancel" button, a pop-up modal will display to prompt the user for confirmation
  * The booking status in the database should be deleted after confirmation
  * A confirmation message will be displayed notifying the user that the booking has been successfully canceled

* Amend Booking
  * When the user selects the "Amend" button, the user will be redirected to the Update your Reservation page
  * The user should be able to modify any editable fields and be able to submit the changes.
  * A confirmation message will be displayed notifying the user that the booking has been successfully updated

## Task
* Cancel Booking
- [x] Create a "Cancel" button
- [x] Create a modal to prompt the user for confirmation
- [x] Create a message to notify the user of a successful cancellation

* Amend Booking
- [x] Create a "Amend" button
- [x] Create a link to redirect the user to the Update your Reservation page
- [x] Create an "Update Booking" button
- [x] Create a confirmation message to notify the user that the booking has been updated successfully
