### ISSUE TITLE
USER STORY: Special Requirements

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#4]
As a  **user**  I can **request  a special requirement** so that ** I can inform the owner in advance of the requirements needed**

## Acceptance Criteria
* There should be an input field for the special requirements which is not required for the user to fill in
* Once the booking is saved, this can be opened through a button using a modal to view the details

## Task
- [x] Create an input field for special requirements
- [x] Add a label in the input field to give the user a hint about where to fill in the additional requirements
- [x] Create a button to view the details of the special requirements through a modal form
