### ISSUE TITLE
USER STORY: Number of Attendees

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#5]
As a  **user**  I can **provide the number of attendees** so that **I can ensure the availability   **

## Acceptance Criteria
* The system should provide a field where I can input the number of attendees
* The input field should only accept numerical values
* The system should display an error message if the number of guest inputs is invalid

## Task
- [x]  Display error message for invalid input
- [x]  Display the current number of attendees
- [x]  Display the input field for the number of attendees

**Comment by Markpm-code** [comment]
## Acceptance Criteria 
- [x] The system should provide a field where I can input the number of guests
- [x] The input field should only accept numerical values
- [x] The system should display an error message if the number of guest inputs is invalid

## Task
- [x] Display error message for invalid input
- [x] Display the current number of guests
- [x] Display the input field for the number of guest
