### ISSUE TITLE
USER STORY: Login or Logout

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#7]
As a  **user**  I can **login or logout** so that ** I can access my personal account and proceed with the booking**

## Acceptance Criteria
* The site should have a "Login or Logout" button at the top of the page together with the navigation menu
* The "Logout" button must display when a user is logged in or authenticated and disappears when logout 
* Once the user is "Logout", the user will have no longer  access to any information related to their account
* The user will be redirected to the homepage once the "Logout" button is clicked

## Task
- [x] Create a "Login and Logout" buttons at the top of the homepage
- [x] Create Login and Logout forms
- [x] Redirect the user to the Login and Logout page if the corresponding buttons are clicked
- [x] Perform testing of the login and logout functionality
