### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by Markpm-code** [Markpm-code/st_benedict_shrine#8]
As a  **user**  I can **register for an account** so that ** I can have a personal account to manage my booking**

## Acceptance Criteria
* The site allows the users to access the account registration page by clicking the "Sign Up or Login " button on the homepage
* The Sign-Up page must include fields for the user to enter their e-mail address, password, and password confirmation
* Upon successful registration, the user should be redirected to the homepage and automatically logged in with the new account

## Task
- [x] Verify that the "Sign up or Login" button on the homepage redirects the user to the account sign-up or login page
- [x] Display validation errors if the user enters the wrong email format and if the password does not match
- [x] Create a welcome message to the user at the top of the homepage once logged in
- [x]  Create a "Reservations" button that will redirect the user to the reservations page
